In [1]:
import numpy as np
from tqdm import tqdm

RESHAPE = (9, 9)

In [4]:
quizzes = np.zeros((100001, 81), np.int32)
solutions = np.zeros((100001, 81), np.int32)
for i, line in tqdm(enumerate(open('sudoku.csv', 'r').read().splitlines()[1:])):
    quiz, solution = line.split(",")
    for j, q_s in enumerate(zip(quiz, solution)):
        q, s = q_s
        quizzes[i, j] = q
        solutions[i, j] = s
    if i == 100000:
        break
# quizzes = quizzes.reshape((-1, 9, 9))
# solutions = solutions.reshape((-1, 9, 9))

100000it [00:09, 10736.18it/s]


In [69]:
def checkMostFreq(quiz):
    quiz = list(quiz)
    countDict = dict()
    for i in range(1, 10):
        countDict[i] = quiz.count(i)
    max_count, max_id = 0, 0
    for k,v in countDict.items():
        if v > max_count:
            max_id = k
            max_count = v
    return max_id

def transformer(val):
    return (val // 9, val % 9)

def validLocations(quiz, id):
    invalid_indeices, valid_locations = set(), []
    for i in range(81):
        if quiz[i] == id:
            row, col = i // 9, i % 9
            need_remove_row = set(range(row * 9, (row + 1) * 9))
            need_remove_col = set(range(col, 73 + col, 9))
            squ_row, squ_col = row // 3, col // 3
            need_remove_squ = set(list(range(squ_row * 27 + squ_col * 3, squ_row * 27 + squ_col * 3 + 3)) 
            + list(range(squ_row * 27 + squ_col * 3 + 9, squ_row * 27 + squ_col * 3 + 12))
            + list(range(squ_row * 27 + squ_col * 3 + 18, squ_row * 27 + squ_col * 3 + 21)))
            invalid_indeices = invalid_indeices | need_remove_row | need_remove_col | need_remove_squ
        elif quiz[i] != 0:
            invalid_indeices.add(i)
    valid_indeices = list(set(range(81)) - invalid_indeices)
    for i in valid_indeices:
        valid_locations.append(transformer(i))
    return valid_locations

In [72]:
quiz = quizzes[1]
quiz_ = quiz.reshape(RESHAPE)
print(quiz_)
validLocations(quiz, 5)

[[0 4 0 1 0 0 0 5 0]
 [1 0 7 0 0 3 9 6 0]
 [5 2 0 0 0 8 0 0 0]
 [0 0 0 0 0 0 0 1 7]
 [0 0 0 9 0 6 8 0 0]
 [8 0 3 0 5 0 6 2 0]
 [0 9 0 0 6 0 5 4 3]
 [6 0 0 0 8 0 7 0 0]
 [2 5 0 0 9 7 1 0 0]]


[(7, 3), (7, 5), (4, 2), (1, 3), (4, 8), (3, 2)]